// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_direction_turn_straight_png);    // assets/direction_turn_straight.png
LV_IMG_DECLARE(ui_img_direction_close_png);    // assets/direction_close.png
LV_IMG_DECLARE(ui_img_direction_flag_png);    // assets/direction_flag.png
LV_IMG_DECLARE(ui_img_direction_roundabout_png);    // assets/direction_roundabout.png
LV_IMG_DECLARE(ui_img_direction_turn_left_png);    // assets/direction_turn_left.png
LV_IMG_DECLARE(ui_img_direction_turn_right_png);    // assets/direction_turn_right.png
LV_IMG_DECLARE(ui_img_direction_turn_sharp_left_png);    // assets/direction_turn_sharp_left.png
LV_IMG_DECLARE(ui_img_direction_turn_sharp_right_png);    // assets/direction_turn_sharp_right.png
LV_IMG_DECLARE(ui_img_direction_turn_slight_left_png);    // assets/direction_turn_slight_left.png
LV_IMG_DECLARE(ui_img_direction_turn_slight_right_png);    // assets/direction_turn_slight_right.png
LV_IMG_DECLARE(ui_img_direction_uturn_png);    // assets/direction_uturn.png

// FONTS
LV_FONT_DECLARE(ui_font_lvfontnotoserif14);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
