// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
static bool is_flipped = false;
void bg_click(lv_event_t * e)
{
	// lv_display_t * disp = lv_obj_get_display(ui_Screen1);
	// if (is_flipped) {
	// 	// Reset to normal rotation (based on current 480x320 rotation=1)
	// 	lv_display_set_rotation(disp, LV_DISPLAY_ROTATION_0);
	// 	is_flipped = false;
	// } else {
	// 	// Flip by rotating 270 degrees (270 = 90 + 180 flip)
	// 	lv_display_set_rotation(disp, LV_DISPLAY_ROTATION_180);
	// 	is_flipped = true;
	// }
}
