// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_pgDistanceBar;
extern lv_obj_t * ui_lbRoad;
extern lv_obj_t * ui_imgDirection;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_lbStatus;
extern lv_obj_t * ui_lbBT;
extern lv_obj_t * ui_lbETA;
extern lv_obj_t * ui_lbDistance;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_lbSpeed;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_lbLimit;
// CUSTOM VARIABLES
extern lv_obj_t * uic_pgDistanceBar;
extern lv_obj_t * uic_lbRoad;
extern lv_obj_t * uic_imgDirection;
extern lv_obj_t * uic_lbStatus;
extern lv_obj_t * uic_lbBT;
extern lv_obj_t * uic_lbETA;
extern lv_obj_t * uic_lbDistance;
extern lv_obj_t * uic_lbSpeed;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

