// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_lbSpeed;
lv_obj_t * uic_lbDistance;
lv_obj_t * uic_lbETA;
lv_obj_t * uic_lbBT;
lv_obj_t * uic_lbStatus;
lv_obj_t * uic_imgDirection;
lv_obj_t * uic_lbRoad;
lv_obj_t * uic_pgDistanceBar;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_pgDistanceBar = NULL;
lv_obj_t * ui_lbRoad = NULL;
lv_obj_t * ui_imgDirection = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_lbStatus = NULL;
lv_obj_t * ui_lbBT = NULL;
lv_obj_t * ui_lbETA = NULL;
lv_obj_t * ui_lbDistance = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_lbSpeed = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_lbLimit = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        bg_click(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pgDistanceBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_pgDistanceBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_pgDistanceBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_pgDistanceBar, 470);
    lv_obj_set_height(ui_pgDistanceBar, 10);
    lv_obj_set_x(ui_pgDistanceBar, 0);
    lv_obj_set_y(ui_pgDistanceBar, -5);
    lv_obj_set_align(ui_pgDistanceBar, LV_ALIGN_BOTTOM_MID);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_pgDistanceBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_pgDistanceBar,
                                                                                                    lv_obj_get_style_pad_right(ui_pgDistanceBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lbRoad = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbRoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbRoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbRoad, 0);
    lv_obj_set_y(ui_lbRoad, -20);
    lv_obj_set_align(ui_lbRoad, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbRoad, "Nam An Khánh");
    lv_obj_set_style_text_color(ui_lbRoad, lv_color_hex(0x00C5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbRoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbRoad, &ui_font_lvfontnotoserif14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgDirection = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_imgDirection, &ui_img_direction_turn_straight_png);
    lv_obj_set_width(ui_imgDirection, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgDirection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgDirection, -137);
    lv_obj_set_y(ui_imgDirection, -21);
    lv_obj_set_align(ui_imgDirection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgDirection, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgDirection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_header, 480);
    lv_obj_set_height(ui_header, 30);
    lv_obj_set_align(ui_header, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbStatus = lv_label_create(ui_header);
    lv_obj_set_width(ui_lbStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lbStatus, "Status");

    ui_lbBT = lv_label_create(ui_header);
    lv_obj_set_width(ui_lbBT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbBT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbBT, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lbBT, "BT: Disconnected");

    ui_lbETA = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbETA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbETA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbETA, 100);
    lv_obj_set_y(ui_lbETA, 60);
    lv_obj_set_align(ui_lbETA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbETA, "ETA: 23:04");
    lv_obj_set_style_text_color(ui_lbETA, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbETA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbETA, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbDistance = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbDistance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbDistance, -137);
    lv_obj_set_y(ui_lbDistance, 102);
    lv_obj_set_align(ui_lbDistance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbDistance, "Distance");
    lv_obj_set_style_text_font(ui_lbDistance, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 100);
    lv_obj_set_height(ui_Panel1, 100);
    lv_obj_set_x(ui_Panel1, 162);
    lv_obj_set_y(ui_Panel1, -30);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x00C5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel2, 80);
    lv_obj_set_height(ui_Panel2, 80);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbSpeed = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_lbSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSpeed, 0);
    lv_obj_set_y(ui_lbSpeed, 1);
    lv_obj_set_align(ui_lbSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSpeed, "112");
    lv_obj_set_style_text_color(ui_lbSpeed, lv_color_hex(0x00C5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbSpeed, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 100);
    lv_obj_set_height(ui_Panel3, 100);
    lv_obj_set_x(ui_Panel3, 26);
    lv_obj_set_y(ui_Panel3, -30);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel4, 80);
    lv_obj_set_height(ui_Panel4, 80);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbLimit = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_lbLimit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbLimit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbLimit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbLimit, "120");
    lv_obj_set_style_text_color(ui_lbLimit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbLimit, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);
    uic_pgDistanceBar = ui_pgDistanceBar;
    uic_lbRoad = ui_lbRoad;
    uic_imgDirection = ui_imgDirection;
    uic_lbStatus = ui_lbStatus;
    uic_lbBT = ui_lbBT;
    uic_lbETA = ui_lbETA;
    uic_lbDistance = ui_lbDistance;
    uic_lbSpeed = ui_lbSpeed;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_pgDistanceBar = NULL;
    ui_pgDistanceBar = NULL;
    uic_lbRoad = NULL;
    ui_lbRoad = NULL;
    uic_imgDirection = NULL;
    ui_imgDirection = NULL;
    ui_header = NULL;
    uic_lbStatus = NULL;
    ui_lbStatus = NULL;
    uic_lbBT = NULL;
    ui_lbBT = NULL;
    uic_lbETA = NULL;
    ui_lbETA = NULL;
    uic_lbDistance = NULL;
    ui_lbDistance = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    uic_lbSpeed = NULL;
    ui_lbSpeed = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;
    ui_lbLimit = NULL;

}
